### ISSUE TITLE
Pre-reqs

### ISSUE THREAD

**Issue by goffinf** [deptno/cwlog#3]
Interesting capability.

Can you update the README to include any pre-requisites that would typically be required to run the utility. For example, what would the minimum set of IAM privileges be ? ... are there any constraints in respect of data that is stored in Cloudwatch that would not be serialisable into JSON, and so on.

Thx

**Comment by deptno** [comment]
I think It's essential knowledge, but specify **cwlog get credential from $HOME/aws/credential** to `readme.md` makes clear to understand privileges.

If you want update README. feel free to make a pull request.

**Comment by deptno** [comment]
inactive
