### ISSUE TITLE
로그 그룹 개수가 50개가 넘어가는 경우, 첫 50개만 보여줍니다.

### ISSUE THREAD

**Issue by dennis-zent** [deptno/cwlog#4]
로그 그룹 개수가 50개가 넘어가는 경우, 첫 50개만 보여줍니다.

**Comment by deptno** [comment]
제보 감사합니다. 일단 제가 최근 로그만 필요해서 그렇게 만들었습니다. 😓 

로그 그룹 개수가 50개가 넘어가는경우 페이지네이션이나 아니면 한번에 모든 데이터를 다운받는 형식이 데이터 핸들링이 필요하게되는데요

페이지네이션 같은 경우는 터미널과 라이브러리 의존성을 볼때 수동 구현형태가 되어 구현난이도가 좀 있어보이고( 한번에 모든 데이터를 다운 받자니 `Inquirer.js` 제약상 이를 위아래로 이동하는 것 또한 이슈라 좀 고민이 있네요.

일단 로그 이벤트 스트림이 아닌 로그 그룹자체가 보이지 않는 것은 크리티컬 하므로 태그를 달아 놓겠습니다.

**로그 그룹과 관련해서는 아무래도 전체를 다 다운로드 받는게 편하게 사용성을 높일 수 있을 것 같습니다.**

제보 감사합니다.

**Comment by dennis-zent** [comment]
친절한 설명 감사합니다. :)
